# Python Jupyter
https://www.linkedin.com/in/burakhan-sinal/

Example: Python implementation of the classic quicksort algorithm:

In [1]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


# Basic data types


In [3]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints “3"
print(x + 1)   # Addition; prints “4"
print(x - 1)   # Subtraction; prints “2"
print(x * 2)   # Multiplication; prints “6"
print(x ** 2)  # Exponentiation; prints “9"
x += 1
print(x)  # Prints “4"
x *= 2
print(x)  # Prints “8"
y = 3.7
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints “3.7 4.7 7.4 13.69"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
3.7 4.7 7.4 13.690000000000001


# Basic data types


In [3]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


# Basic data types


In [4]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello
5
hello world
hello world 12


In [5]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  			hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with 			another;
                       # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints 				"world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


# Containers



In [6]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-3])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
3
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


# Lists


In [7]:
nums = list(range(5))     # range is a built-in function that 				creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 					(exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; 				prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 				(exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints 				"[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints 				"[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


# Containers -> lists -> Loops


In [8]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [9]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
		# Prints "#1: cat", "#2: dog", "#3: 				monkey", each on its own line

#1: cat
#2: dog
#3: monkey


# Containers -> lists -> List comprehension


In [10]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [11]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [12]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

[0, 4, 16]


# Containers -> dictionaries


In [13]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary 		with some data
print(d['cat'])       # Get an entry from a dictionary; prints 		"cute"
print('cat' in d)     # Check if a dictionary has a given key; 		prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; 		prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; 		prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints 			"N/A"

cute
True
wet
N/A
wet
N/A


# Containers -> dictionaries-> Loops


In [16]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [17]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


# Containers -> dictionaries comprehensions


In [18]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


# Sets


In [19]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; 	prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints 	"3"
animals.add('cat')        # Adding an element that is already in 				the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

True
False
True
3
3
2


# Sets


In [19]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: dog
#3: cat


In [20]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


# Tuples


In [21]:
d = {(x, x + 1): x for x in range(10)}  # Create a 				dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


# Functions


In [22]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"

negative
zero
positive


# Functions


In [23]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


# Classes


In [25]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


# NumPy
The topic of NumPy and pandas libraries refers to datasets can come from a wide range of sources and in a wide range of formats, including: 
- collections of documents, 
- collections of images, 
- collections of sound clips, 
- collections of numerical measurements, or 
- … nearly anything technical issues. 
Data sets can be represented as arrays of numbers.
- digital images—can be thought of as simply two-dimensional arrays of numbers representing pixel brightness across the area. 
- sound clips can be thought of as one-dimensional arrays of intensity versus time. 
- text can be converted in various ways into numerical representations, such as binary digits representing the frequency of - certain words or pairs of words. 
Efficient storage and manipulation of numerical arrays is fundamental to the process of doing data science. 
Install NumPy : http://www.numpy.org/ 
The import NumPy and for example double-check the version:

In [24]:
import numpy
numpy.__version__

'1.24.3'

In [25]:
import numpy as np

# Now we can use np.array to create arrays from Python lists:


In [26]:
# Integer array
np.array([1, 4, 2, 5, 3])
# Float number aray
np.array([3.14, 4, 2, 3])
# or use the dtype keyword:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [27]:
# Nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Arrays from Scratch


In [28]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [31]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
# Create a 3x3 array of uniformly distributed
# pseudorandom values between 0 and 1
np.random.random((3, 3))

array([[0.42989293, 0.92468543, 0.37951455],
       [0.57787259, 0.76435703, 0.96925972],
       [0.27857577, 0.57787546, 0.3487548 ]])

In [34]:
# Create a 3x3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.26337171,  0.68400431, -1.17398922],
       [-1.57472291, -0.31799527,  0.29388114],
       [-0.94012222,  1.8299793 ,  0.26340028]])

In [35]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[0, 7, 2],
       [5, 6, 0],
       [2, 6, 1]])

In [36]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# Create an uninitialized array of three integers; the values will be
# whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

# np.zeros


In [38]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [39]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

# NumPy Array random number generator

NumPy Array Attributes
First let's discuss some useful array attributes. We'll start by defining random arrays of one, two, and three dimensions. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [40]:
import numpy as np
rng = np.random.default_rng(seed=1701)  # seed for reproducibility

x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array
# list x1,x2,x3

Each array has attributes including ndim (the number of dimensions), shape (the size of each dimension), size (the total size of the array), and dtype (the type of each element):

In [41]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


# Array Indexing: Accessing Single Elements
the 𝑖𝑡ℎ value (counting from zero) can be accessed by specifying the desired index in square brackets

In [42]:
x1
# x1[0]
# x1[4]

array([9, 4, 0, 3, 8, 6], dtype=int64)

In a multidimensional array, items can be accessed using a comma-separated (row, column) tuple:

In [43]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [44]:
x2[2,0]
x2[2,-1]

9

## Array Slicing: Accessing Subarrays
Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

x[start:stop:step]
If any of these are unspecified, they default to the values start=0, stop=<size of dimension>, step=1. Let's look at some examples of accessing subarrays in one dimension and in multiple dimensions.

In [45]:
# One-Dimensional Subarrays
#x1
#x1[:3]
#x1[3:]
#x1[1:4]
#x1[::2] # every second element
#x1[1::2] # every second element, starting at index 1
#x1[::-1] # all elements, reversed
x1[4::-2] # every second element from index 4, reversed

array([8, 0, 9], dtype=int64)

## Multidimensional Subarrays
Multidimensional slices work in the same way, with multiple slices separated by commas.

In [46]:
x2
#x2[:2,:3] # first two rows & three columns
#x2[:3,::2]  # three rows, every second column
#x2[::-1, ::-1]  # all rows & columns, reversed

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

### Subarrays as No-Copy Views
Unlike Python list slices, NumPy array slices are returned as views rather than copies of the array data. Consider our two-dimensional array from before:

In [47]:
print(x2)
x2_sub = x2[:2, :2]
print(x2_sub)
x2_sub[0, 0] = 99 # if we modify this subarray, we'll see that the original array is changed
print(x2_sub)
print(x2) # element [0,0] in array x2 is also changed

[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
[[3 1]
 [4 0]]
[[99  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


## Creating Copies of Arrays
Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy method:

In [56]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[99  1]
 [ 4  0]]
[[42  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


## Reshaping of Arrays
Another useful type of operation is reshaping of arrays, which can be done with the reshape method. For example, if you want to put the numbers 1 through 9 in a  3×3
  grid, you can do the following:

In [57]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


converting a one-dimensional array into a two-dimensional row or column matrix:

In [49]:
x = np.array([1, 2, 3])
print(x)
x.reshape((1, 3))  # row vector via reshape
print(x)
x.reshape((3, 1))  # column vector via reshape
print(x)
#  use np.newaxis in the slicing syntax:
x[np.newaxis, :]  # row vector via newaxis
print(x)
x[:, np.newaxis]  # column vector via newaxis
print(x)

[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]


# Array Concatenation and Splitting

## concatenation

In [69]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])
# concatenation more than two arrays at once:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))
# for two-dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

[ 1  2  3  3  2  1 99 99 99]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [71]:
# for working with arrays of mixed dimensions, 
# to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [72]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

## Splitting of arrays

In [73]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [74]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [76]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#Burakhan Sinal 
#https://www.linkedin.com/in/burakhan-sinal/
